### ISSUE TITLE
请问这个lua文件是怎么导出来的啊

### ISSUE THREAD

**Issue by huangzhex** [Oyaxira/mjh_lua#1]

**Comment by Oyaxira** [comment]
AssetStudio

https://github.com/Perfare/AssetStudio

**Comment by huangzhex** [comment]
我导出了的lua文件都是乱码。请问能反编译成源文件？

**Comment by Oyaxira** [comment]
不太可能全是乱码,你用vscode打开瞅瞅.
部分文件乱码是因为格式是gbk,vscode默认utf-8打开的.
我记得我遇到过这样的文件处理过.
不存在反编译成原文件的可能性.
你想修改游戏的话只能用另外的工具重新倒回asset里边去. 具体请查阅unity游戏修改.b站和谷歌搜一下应该很多有详细的.

**Comment by huangzhex** [comment]
非常感谢您的回复，确实lua文件中不全是乱码有中文，但代码部分是乱码。我把文件推送到github上了，https://github.com/huangzhex/mjh_lua/tree/xin/me

**Comment by Oyaxira** [comment]
你这个解的好像不太对吧...怎么都是二进制文件
